# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 22 Apr 2021 19:13:03 +0000
*               @ALL          1
*               @user         8
