<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: ventarc
 * Date: Sat, 15 May 2021 18:45:27 +0100
 */

$conf['title'] = 'Ventarc personal wiki';
$conf['template'] = 'mindthedark';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['tpl']['mindthedark']['theme'] = 'dark';
$conf['tpl']['mindthedark']['autoDark'] = 1;
$conf['tpl']['mindthedark']['userChoice'] = 1;
