# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 22 Apr 2021 19:13:03 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

ventarc:$2y$10$6ShF5bxm9qHu64uHe1qLJeUMa8CEIuLqTLKUoz5rfwr5VlHBbP5TS:VentArc:fabiofasiello.ctf@gmail.com:admin,user
